# Generated by Django 4.0.6 on 2023-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctorphone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='book',
        ),
        migrations.AlterField(
            model_name='client',
            name='clientType',
            field=models.CharField(default='Ordinary', max_length=200),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
