# Generated by Django 4.0.6 on 2023-03-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_treatment_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='paid',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.medicalrecord'),
        ),
    ]
