# Generated by Django 4.0.6 on 2023-03-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.company'),
        ),
    ]
